default: &default
  adapter: postgresql
  encoding: unicode
  pool: 30
  username: ENV['DB_USERNAME']
  password: ENV['DB_PASSWORD']
  host: ENV['DB_HOST']

development:
  <<: *default
  database: customer_app_dev

test:
  <<: *default
  database: customer_app_test
